/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a comment
         * @description Allowed for the comment's own author or an admin.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Comment ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a comment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Comment ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Report reason */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_report.ReportCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_report.Report"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description reporting your own content */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description Returns the authenticated user's notifications, newest first.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_notification.Notification"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all notifications read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread notification count */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.CountResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark one notification read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notification ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all problems */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.ProblemListItem"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a problem
         * @description Any authenticated user may create a problem; no role gate.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description New problem */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_problems.CreateProblemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.ProblemSummary"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.ProblemDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Update a problem
         * @description Allowed for admins (Council/Associate title) on any problem, or the problem's own creator.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Updated fields */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_problems.UpdateProblemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.ProblemRow"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description not the creator and not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a problem
         * @description Allowed for admins (Council/Associate title) on any problem, or the problem's own creator. Also best-effort destroys its Cloudinary images.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a problem's topo annotations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.AnnotationRecord"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Save a topo image's annotation
         * @description One vector-shape overlay per (problem, image_url). Allowed for admins or the problem's own creator.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Image URL and shape data */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_problems.SaveAnnotationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.AnnotationRecord"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description problem or image not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a problem's comments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.Comment"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Add a comment to a problem */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Comment content */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_social.CreateCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.Comment"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one image from a problem */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Image URL to remove */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_problems.DeleteProblemImageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description problem or image not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/images/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a problem's topo image */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Image URL and reason */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_report.ReportImageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_report.Report"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description reporting your own content */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle a send (tick) on this problem */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description action is sent or unsent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.ActionResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/send-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the authenticated user has sent this problem */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Problem ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.SendStatusResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID or slug */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_auth.Profile"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        /** Update a profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Profile fields */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.UpsertProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_auth.Profile"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a profile's recent sends and problems */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID or slug */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_auth.RecentActivity"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total reaction counts on a profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID or slug */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.ReactionCounts"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/reactions/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which reactions the authenticated user gave this profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID or slug */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.ReactionStatus"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/reactions/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle a reaction on a profile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID or slug */
                    id: string;
                    /** @description Reaction type: like, fire, or heart */
                    type: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description action is added or removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_social.ActionResponse"];
                    };
                };
                /** @description invalid reaction type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a profile's aggregate stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID or slug */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_auth.ProfileStats"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending reports
         * @description Admin-only (Council/Associate title) moderation queue.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_report.Report"][];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a report
         * @description Admin-only. Action is either "remove" (deletes the reported content) or "dismiss".
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Report ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Resolution action */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_report.ResolveReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description report already resolved */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a profile avatar
         * @description Streams an image to Cloudinary's kepalabatu_avatars folder, returns its URL.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Image file, max 8MB */
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": Record<string, never>;
                    "multipart/form-data": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.AvatarUploadResponse"];
                    };
                };
                /** @description no file, file too large, or not an image */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description cloudinary upload failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/topo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a topo photo
         * @description Streams an image to Cloudinary's kepalabatu_topos folder, returns its URL.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Image file, max 8MB */
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": Record<string, never>;
                    "multipart/form-data": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_problems.TopoUploadResponse"];
                    };
                };
                /** @description no file, file too large, or not an image */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description cloudinary upload failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join the waitlist
         * @description Adds an email to the pre-launch waitlist. A repeat submission of an already-registered email is treated as a success (already_joined: true), not an error.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email to add */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_waitlist.JoinRequest"];
                };
            };
            responses: {
                /** @description email was already on the waitlist */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_waitlist.AlreadyJoinedResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_waitlist.Subscriber"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the authenticated user's account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Password confirmation */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.DeleteAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.SuccessResponse"];
                    };
                };
                /** @description invalid body or wrong password */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Always returns the same generic success message regardless of whether the email exists, to avoid leaking account existence.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account email */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the authenticated user's password */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Current and new password */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.MessageResponse"];
                    };
                };
                /** @description invalid body, too-short new password, or wrong current password */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Reset token and new password */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.MessageResponse"];
                    };
                };
                /** @description invalid or expired reset link */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_auth.SessionResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Authenticates a user by email and password, returns a JWT and the user record.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.SigninRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_auth.SigninResponse"];
                    };
                };
                /** @description invalid body, bad credentials, or unverified email */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up
         * @description Creates the user + profile rows in one transaction and sends a verification email; the whole signup is rolled back if the email fails to send.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description New account details */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_auth.SignupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Total registered user count
         * @description Backs the landing page's climber-count stat. Unauthenticated, same trust level as GET /problems.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.CountResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify an email address */
        get: {
            parameters: {
                query: {
                    /** @description Verification token */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.MessageResponse"];
                    };
                };
                /** @description invalid or expired token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["palabatu-be_internal_apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "internal_auth.ChangePasswordRequest": {
            current_password?: string;
            new_password?: string;
        };
        "internal_auth.DeleteAccountRequest": {
            password?: string;
        };
        "internal_auth.ForgotPasswordRequest": {
            email?: string;
        };
        "internal_auth.Profile": {
            avatar_url?: string;
            bio?: string;
            created_at?: string;
            id?: string;
            location?: string;
            slug?: string;
            tags?: number[];
            title?: number[];
            username?: string;
        };
        "internal_auth.ProfileStats": {
            problems_count?: number;
            sends_count?: number;
        };
        "internal_auth.RecentActivity": {
            problems?: components["schemas"]["internal_auth.RecentProblem"][];
            sends?: components["schemas"]["internal_auth.RecentSend"][];
        };
        "internal_auth.RecentProblem": {
            created_at?: string;
            grade?: string;
            id?: string;
            name?: string;
        };
        "internal_auth.RecentSend": {
            created_at?: string;
            grade?: string;
            problem_id?: string;
            problem_name?: string;
        };
        "internal_auth.ResetPasswordRequest": {
            password?: string;
            token?: string;
        };
        "internal_auth.SessionResponse": {
            user?: components["schemas"]["internal_auth.User"];
        };
        "internal_auth.SigninRequest": {
            email?: string;
            password?: string;
        };
        "internal_auth.SigninResponse": {
            token?: string;
            user?: components["schemas"]["internal_auth.User"];
        };
        "internal_auth.SignupRequest": {
            email?: string;
            password?: string;
            terms_accepted?: boolean;
            username?: string;
        };
        "internal_auth.UpsertProfileRequest": {
            avatar_url?: string;
            bio?: string;
            location?: string;
            tags?: number[];
            title?: number[];
            username?: string;
        };
        "internal_auth.User": {
            email?: string;
            id?: string;
            slug?: string;
            username?: string;
        };
        "internal_notification.Notification": {
            actor_name?: string;
            created_at?: string;
            id?: string;
            message?: string;
            problem_id?: string;
            problem_name?: string;
            read?: boolean;
            type?: components["schemas"]["internal_notification.Type"];
        };
        /** @enum {string} */
        "internal_notification.Type": "comment" | "send" | "report_resolved" | "content_removed" | "reaction" | "problem_edited" | "problem_deleted" | "mention";
        "internal_problems.AnnotationRecord": {
            created_at?: string;
            data?: number[];
            id?: string;
            image_url?: string;
            problem_id?: string;
            updated_at?: string;
            updated_by?: string;
        };
        "internal_problems.AvatarUploadResponse": {
            avatar_url?: string;
        };
        "internal_problems.CreateProblemRequest": {
            grade?: string;
            image_urls?: string[];
            lat?: number;
            lng?: number;
            location?: string;
            name?: string;
        };
        "internal_problems.DeleteProblemImageRequest": {
            url?: string;
        };
        "internal_problems.ProblemDetail": {
            created_at?: string;
            created_by?: string;
            creator_name?: string;
            creator_slug?: string;
            grade?: string;
            id?: string;
            image_urls?: string[];
            latitude?: number;
            location_name?: string;
            longitude?: number;
            name?: string;
            send_count?: number;
        };
        "internal_problems.ProblemListItem": {
            created_at?: string;
            created_by?: string;
            creator_name?: string;
            creator_slug?: string;
            grade?: string;
            id?: string;
            image_urls?: string[];
            latitude?: number;
            location_name?: string;
            longitude?: number;
            name?: string;
            send_count?: number;
        };
        "internal_problems.ProblemRow": {
            created_at?: string;
            created_by?: string;
            grade?: string;
            id?: string;
            image_urls?: string[];
            lat?: number;
            lng?: number;
            location?: string;
            name?: string;
        };
        "internal_problems.ProblemSummary": {
            grade?: string;
            id?: string;
            latitude?: number;
            location_name?: string;
            longitude?: number;
            name?: string;
        };
        "internal_problems.SaveAnnotationRequest": {
            data?: number[];
            url?: string;
        };
        "internal_problems.TopoUploadResponse": {
            url?: string;
        };
        "internal_problems.UpdateProblemRequest": {
            grade?: string;
            lat?: number;
            lng?: number;
            location_name?: string;
            name?: string;
        };
        "internal_report.Report": {
            comment_content?: string;
            comment_id?: string;
            created_at?: string;
            id?: string;
            image_url?: string;
            problem_id?: string;
            problem_name?: string;
            reason?: string;
            reporter_id?: string;
            reporter_name?: string;
            status?: string;
            target_type?: string;
        };
        "internal_report.ReportCommentRequest": {
            reason?: string;
        };
        "internal_report.ReportImageRequest": {
            reason?: string;
            url?: string;
        };
        "internal_report.ResolveReportRequest": {
            action?: string;
        };
        "internal_social.ActionResponse": {
            action?: string;
        };
        "internal_social.Comment": {
            content?: string;
            created_at?: string;
            id?: string;
            user_id?: string;
            user_slug?: string;
            username?: string;
        };
        "internal_social.CreateCommentRequest": {
            content?: string;
        };
        "internal_social.ReactionCounts": {
            fire?: number;
            heart?: number;
            like?: number;
        };
        "internal_social.ReactionStatus": {
            fire?: boolean;
            heart?: boolean;
            like?: boolean;
        };
        "internal_social.SendStatusResponse": {
            hasSent?: boolean;
        };
        "internal_waitlist.AlreadyJoinedResponse": {
            already_joined?: boolean;
        };
        "internal_waitlist.JoinRequest": {
            email?: string;
        };
        "internal_waitlist.Subscriber": {
            created_at?: string;
            email?: string;
            id?: string;
        };
        "palabatu-be_internal_apitypes.CountResponse": {
            count?: number;
        };
        "palabatu-be_internal_apitypes.ErrorResponse": {
            error?: string;
        };
        "palabatu-be_internal_apitypes.MessageResponse": {
            message?: string;
        };
        "palabatu-be_internal_apitypes.SuccessResponse": {
            success?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
